// source: nock/input.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.Anoma.Protobuf.Nock.Input', null, global);
goog.exportSymbol('proto.Anoma.Protobuf.Nock.Input.InputCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Anoma.Protobuf.Nock.Input = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.Anoma.Protobuf.Nock.Input.oneofGroups_);
};
goog.inherits(proto.Anoma.Protobuf.Nock.Input, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Anoma.Protobuf.Nock.Input.displayName = 'proto.Anoma.Protobuf.Nock.Input';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.Anoma.Protobuf.Nock.Input.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.Anoma.Protobuf.Nock.Input.InputCase = {
  INPUT_NOT_SET: 0,
  JAMMED: 1,
  TEXT: 2
};

/**
 * @return {proto.Anoma.Protobuf.Nock.Input.InputCase}
 */
proto.Anoma.Protobuf.Nock.Input.prototype.getInputCase = function() {
  return /** @type {proto.Anoma.Protobuf.Nock.Input.InputCase} */(jspb.Message.computeOneofCase(this, proto.Anoma.Protobuf.Nock.Input.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Anoma.Protobuf.Nock.Input.prototype.toObject = function(opt_includeInstance) {
  return proto.Anoma.Protobuf.Nock.Input.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Anoma.Protobuf.Nock.Input} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Anoma.Protobuf.Nock.Input.toObject = function(includeInstance, msg) {
  var f, obj = {
jammed: msg.getJammed_asB64(),
text: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Anoma.Protobuf.Nock.Input}
 */
proto.Anoma.Protobuf.Nock.Input.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Anoma.Protobuf.Nock.Input;
  return proto.Anoma.Protobuf.Nock.Input.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Anoma.Protobuf.Nock.Input} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Anoma.Protobuf.Nock.Input}
 */
proto.Anoma.Protobuf.Nock.Input.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setJammed(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setText(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Anoma.Protobuf.Nock.Input.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Anoma.Protobuf.Nock.Input.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Anoma.Protobuf.Nock.Input} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Anoma.Protobuf.Nock.Input.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional bytes jammed = 1;
 * @return {string}
 */
proto.Anoma.Protobuf.Nock.Input.prototype.getJammed = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes jammed = 1;
 * This is a type-conversion wrapper around `getJammed()`
 * @return {string}
 */
proto.Anoma.Protobuf.Nock.Input.prototype.getJammed_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getJammed()));
};


/**
 * optional bytes jammed = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getJammed()`
 * @return {!Uint8Array}
 */
proto.Anoma.Protobuf.Nock.Input.prototype.getJammed_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getJammed()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.Anoma.Protobuf.Nock.Input} returns this
 */
proto.Anoma.Protobuf.Nock.Input.prototype.setJammed = function(value) {
  return jspb.Message.setOneofField(this, 1, proto.Anoma.Protobuf.Nock.Input.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Anoma.Protobuf.Nock.Input} returns this
 */
proto.Anoma.Protobuf.Nock.Input.prototype.clearJammed = function() {
  return jspb.Message.setOneofField(this, 1, proto.Anoma.Protobuf.Nock.Input.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Anoma.Protobuf.Nock.Input.prototype.hasJammed = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string text = 2;
 * @return {string}
 */
proto.Anoma.Protobuf.Nock.Input.prototype.getText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Anoma.Protobuf.Nock.Input} returns this
 */
proto.Anoma.Protobuf.Nock.Input.prototype.setText = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.Anoma.Protobuf.Nock.Input.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Anoma.Protobuf.Nock.Input} returns this
 */
proto.Anoma.Protobuf.Nock.Input.prototype.clearText = function() {
  return jspb.Message.setOneofField(this, 2, proto.Anoma.Protobuf.Nock.Input.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Anoma.Protobuf.Nock.Input.prototype.hasText = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.Anoma.Protobuf.Nock);
